# Welcome to Sinai Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: 1.0.1

# Site settings
title: Unf*ck The Earth
email: blog@unfuckthe.earth
description: >- # this means to ignore newlines until "baseurl:"
  I'm a software engineer that want to do more to help save the climate, but I don't knwo how.
  This blog documents my journey in search of a way to get involved.
author:
  Gidi Meir Morris
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://www.unfuckthe.earth' # The base hostname & protocol for your site
twitter:            https://twitter.com/chekofif

markdown:  kramdown
permalink: pretty
paginate:  20
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext